
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbtxeneta'
version: '1.0.0'

vars:
  start_date: 2021-01-01
  end_date: 2022-06-01
  origin_port_id: CNNBO
  destination_port_id: CAVAN
  origin_region: China East Main
  destination_region: Washington Ports
  num_companies: 5
  num_suppliers: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbtxeneta'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbtxeneta:
    # Config indicated by + and applies to all files under models/src/
    staging:
      +materialized: table
      +schema: staging
    final:
      +materialized: table
      +schema: final

